### ISSUE TITLE
Where is the video tutorial on WEB

### ISSUE THREAD

**Issue by peterchen2001** [BayatGames/Support#10]

**Comment by hasanbayatme** [comment]
Hello.
It is available on our YouTube channel, but the below is the link to the PHP MySQL setup:

- [YouTube Channel](https://www.youtube.com/channel/UCDLJbvqDKJyBKU2E8TMEQpQ)
- [Tutorial Video](https://www.youtube.com/watch?v=DofXOOZ2LAg)

Thanks.
