### ISSUE TITLE
Problem with SaveGameTypeManager

### ISSUE THREAD

**Issue by DavidBours** [BayatGames/Support#13]
Hello,

I bought Same game pro but I have a problem with the SaveGameTypeManager. When my project starts and passing in the Initialize method no types are added.

Regards

**Comment by hasanbayatme** [comment]
Hi.

Do you mean your custom types or the built-in types?
Also, how did you make sure it is not being added and there is no type?

Thanks.
Best Regards.

**Comment by DavidBours** [comment]
Hi,

These are the  both, the process generate a Reflection Type Load Exception on this line:
 (Type[] typesFound = AppDomain.CurrentDomain.GetAssemblies().SelectMany(s => s.GetTypes()).Where(p => type.IsAssignableFrom(p) && !p.IsInterface && !p.IsAbstract).ToArray();) on the SaveGameTypeManager.

I found the problem, it's because I used the following parameters for my project:
Scripting runtime version: .NET 4.x equivalent
Api Compatibility Level: .NET 4.x

I created an other project with the following parameters for my project:
Scripting runtime version: .NET 3.5 equivalent
Api Compatibility Level: .NET 2.0 Subset

With these parameters, it's works but I must to use .NET 4.x because I used the external DLL with this framework.

Thanks,
Regards.

**Comment by hasanbayatme** [comment]
I think it is trying to get that External DLL which causes this issue, as you have mentioned.
So, I have added a new symbol for forcing it to use Manual Type additions.
Please use this and let me know if it works.

### Instructions

1. Download the file [**SaveGameTypeManager.zip**](https://github.com/BayatGames/Support/files/3021976/SaveGameTypeManager.zip)
2. Replace the file at 
```
Assets/BayatGames/SaveGamePro/Scripts/Serialization
```
3. Add this symbol to **Scripting Define Symbols**:
```
SGP_FORCE_MANUAL_TYPES
```
4. Let me know if it works 🎉

**Comment by DavidBours** [comment]
It works now.

Thank you very much.

Regards
