### ISSUE TITLE
PHP MySQL Integration issue

### ISSUE THREAD

**Issue by Sapiains** [BayatGames/Support#17]
Hi there! I have a problem with the PHP MYSQL integration. I downloaded the files to my windows VPS server, and when installing the following error appears:

"MySQL Connection Failed, See the below for more details:
php_network_getaddresses: getaddrinfo failed: Host desconocido. "

my server works fine, and the database is working. Does it require any special features of the server? Should I install something before?

thanks!

**Comment by hasanbayatme** [comment]
Hello mate.
Just letting you know, I'll check this case tomorrow, sorry for delay and thanks for your patience.

**Comment by Sapiains** [comment]
> Hello mate.
> Just letting you know, I'll check this case tomorrow, sorry for delay and thanks for your patience.

hello again, I managed to install it in another hosting, but not in the VPS

**Comment by hasanbayatme** [comment]
By the way, This section at [install.php#L31](https://github.com/BayatGames/php-savegamepro-mysql/blob/903d5153d7bfe083b0e636487924110d6a3362bf/install.php#L31) connects to your database.
Maybe you provide wrong details or maybe your PHP or MySQL version is old.
