### ISSUE TITLE
Save system doesnt work on android.

### ISSUE THREAD

**Issue by MrSitak** [BayatGames/Support#20]
Hello, I've created a game that uses your save system.
 If I use it in unity on my computer (windows), everything works fine, but if I export the game to android, save system stops working and nothing is saved.

Can you help me please?

**Comment by hasanbayatme** [comment]
Hello.
How did you make sure it doesn't save anything? Did you check the files or you just tried to load the data and it loaded nothing?

On Android the file save path is:
```
 /storage/emulated/0/Android/data/<packagename>/files
```

**Comment by hasanbayatme** [comment]
I've exported the demos to my Android device again and tested, the data is saved and loaded back successfully, you can check the files created in the below screenshot:
![Screenshot_2020-02-10-00-00-38-669_com mi android globalFileexplorer](https://user-images.githubusercontent.com/18309454/74109448-d93d3200-4b98-11ea-87c3-1af2e161fc21.jpg)

**Comment by MrSitak** [comment]
Ok I will try it, thank you for your willingness to help.

ne 9. 2. 2020 v 21:34 odesílatel Hasan Bayat <notifications@github.com>
napsal:

**Comment by MrSitak** [comment]
Hello, so I looked into the files folder and there is nothing other than
the Unity folder.


[image: 7eEw.png]
[image: Screenshot_20200210-113514_My Files.jpg]

po 10. 2. 2020 v 10:52 odesílatel Vojtěch Sitař <sitakczech@gmail.com>
napsal:

**Comment by hasanbayatme** [comment]
Unfortunately, your images are not shown here, may you send them again?

**Comment by MrSitak** [comment]
Oh, maybe now?

https://imgur.com/a/yyk9Mo7

po 10. 2. 2020 v 11:44 odesílatel Hasan Bayat <notifications@github.com>
napsal:

**Comment by hasanbayatme** [comment]
I see now ... but that's weird, do you get any errors after saving the data?

If you can attach the logs after debugging and if you get errors, that would be helpful.

Thanks.

**Comment by MrSitak** [comment]
Hello, I solved the problem, it was my fault in script (I loaded before the
save file existed).
But thank you for your  willingness and help anyway. :)   (sorry for my
english)





po 10. 2. 2020 v 16:47 odesílatel Hasan Bayat <notifications@github.com>
napsal:

**Comment by hasanbayatme** [comment]
Great, glad to know you've fixed it.

Thanks ❤️
