### ISSUE TITLE
How can I Check if there is saved data?

### ISSUE THREAD

**Issue by R0CK3T-DEV** [BayatGames/Support#21]
When I try to check if there is saved data with `SaveGame.Load<string>("SavedGame") != null` , it says that I should use Exists(), but I don't know how to. And if this is a very easy thing, sorry. I'm not very good at Unity C# :/

**Comment by hasanbayatme** [comment]
You can use `Exists` method in this case:
```csharp
if (SaveGame.Exists("SavedGame")) {
     // Load the data here
    SaveGame.Load<string>("SavedGame");
}
```
i hope this helps.

**Comment by R0CK3T-DEV** [comment]
It works! Thank you!
