### ISSUE TITLE
Character does not appear in demo scene included in the free asset pack

### ISSUE THREAD

**Issue by czanfir** [BayatGames/Support#22]
Character does not appear in the demo scene included in the free asset pack (Free Platform Game Assets https://assetstore.unity.com/packages/2d/environments/free-platform-game-assets-85838)
Reproducible on Unity 2019.3.10f1

**Comment by hasanbayatme** [comment]
Thank you for reporting it ❤️ 
That's normal behavior, the demo scene is not updated with the latest Unity versions yet, also there is nothing in the demo scenes except just the Sprites landing there, so I'm not sure you'd find anything useful there.

Cheers.
