### ISSUE TITLE
Cannot Download Asset

### ISSUE THREAD

**Issue by paolotormon** [BayatGames/Support#28]
Hi! The current version of your [asset](https://assetstore.unity.com/packages/2d/environments/free-platform-game-assets-85838#content) is not appearing in the store. 

![error unity editoor](https://user-images.githubusercontent.com/61226023/156963545-d0fa6ea8-8900-4e54-bbb9-dbcc06e32a0b.JPG)
![bought](https://user-images.githubusercontent.com/61226023/156963548-a5da92ee-0c76-4a44-b504-078d1596216f.JPG)
![not appear](https://user-images.githubusercontent.com/61226023/156963550-39788113-5566-4843-a8eb-cac10aa24856.JPG)

**Comment by hasanbayatme** [comment]
Yeah that is an issue on the Unity's side and we've contacted them about it but still no response.

Until then, you can download the free pack from here: https://bayat.itch.io/platform-game-assets

**Comment by hasanbayatme** [comment]
The problem now is completely solved.
