### ISSUE TITLE
LOAD "SAVE SYSTEM"

### ISSUE THREAD

**Issue by Gusuu** [BayatGames/Support#29]
Un Saludo Cordial, compre su producto hace dos semanas aproximadamente, y recién empecé a realizar la prueba para guardar y cargar archivos.
Lo que necesito especificamente es guardar objetos creados en tiempo de ejecución, pero no puedo lograrlo adjunto el error que aparece al probar cargar objetos. Si tuvieran una guia mejor explicada para ello, les agradeceria mucho, muchas gracias...
--------------------------------------------------------------------------------------------------------------------------------
Best Regards, I bought your product about two weeks ago, and I just started testing to save and load files.
What I specifically need is to save objects created at runtime, but I can't achieve it I attach the error that appears when trying to load objects. If you had a better explained guide for it, I would greatly appreciate it, thank you very much...

**Comment by hasanbayatme** [comment]
This is being discussed in the email already so I close this one.
