### ISSUE TITLE
Save/Load of a Dictionary with a custom class crashes because of a NullReferenceException

### ISSUE THREAD

**Issue by devingDev** [BayatGames/Support#3]
Hi, I bought SaveGamePro to ease my work but sadly it won't work as I thought it would.

I created a class which I later changed to a struct to see if that helps. No it does not.

So I this Item class : 

public class Item{
public int item_id;
public int count;
}

Now I have a Dictionary like this:

Dictionary<int,Item> m_myItems;

whereas the int is basically the item_id.

If I now try to load or save I get errors.

Here is the error when saving:

`NullReferenceException: Object reference not set to an instance of an object
SaveGamePro.SaveGameWriter.Write[Item] (Item obj) (at Assets/SaveGamePro/Scripts/SaveGameWriter.cs:115)
SaveGamePro.SaveGameWriter.Write[Int32,Item] (System.Collections.Generic.Dictionary`2 obj) (at Assets/SaveGamePro/Scripts/SaveGameWriter.cs:203)
SaveGamePro.SaveGame.Save[Int32,Item] (System.Collections.Generic.Dictionary`2 obj, System.String identifier) (at Assets/SaveGamePro/Scripts/SaveGame.cs:299)
Inventory.AddItemToPlayerInventory (Int32 item_id, Int32 to_add_count) (at Assets/Scripts/Inventory.cs:408)
Inventory.Update () (at Assets/Scripts/Inventory.cs:317)`

This is how I tried saving : 
`SaveGame.Save<int,Item> (items_player, SAVE_IDENTIFIER_PLAYER_ITEMS);`

and loading is like :
`items_player = SaveGame.LoadDictionary<int,Item>(SAVE_IDENTIFIER_PLAYER_ITEMS);`

I hope you can help me get this right.

Thanks

**Comment by hasanbayatme** [comment]
Hi, thanks for contacting us.

This is very simple, you just need to add a custom type for Save Game Pro to handle the `Item` type.

Follow this tutorial: [How to create custom type?](https://github.com/BayatGames/SaveGamePro/wiki/How-to-create-custom-data-type%3F)

Ask anything here if you can't get it working.

Also, there was no need to buy pro version for saving this kind of data, you can save dictionaries and simple data types using Save Game Free.

Hope this helps.

Thanks.

**Comment by devingDev** [comment]
Thanks for the quick answer ! 

I tried what you said but it still gives me the Exception.

I rightclicked on Assets, Save Game Pro -> Create Save Game Type
I named it Item.
Then I copied it to my Scripts folder.

I edited it like in your example:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SaveGamePro.Types
{

	public class SaveGameTypeItem : SaveGameType
	{

		public SaveGameTypeItem () : base ( typeof ( Item ) )
		{
			

		}

		public override object Read ( SaveGameReader saveGameReader )
		{
			Item i = new Item ();
			Read (saveGameReader, i);
			return i;
		}

		public override void Read(SaveGameReader saveGameReader , object outputObj){
			Item i = (Item)outputObj;
			i.item_id = saveGameReader.Read<int> ();
			i.count = saveGameReader.Read<int> ();
		}

		public override void Write ( object data, SaveGameWriter saveGameWriter )
		{
			Item i = (Item)data;
			saveGameWriter.Write<int> (i.item_id);
			saveGameWriter.Write<int> (i.count);
		}

	}

}`


This line is still failing : 

SaveGame.Save<int,Item> (items_player, SAVE_IDENTIFIER_PLAYER_ITEMS);

with this exception :

`NullReferenceException: Object reference not set to an instance of an object
SaveGamePro.SaveGameWriter.Write[Item] (Item obj) (at Assets/SaveGamePro/Scripts/SaveGameWriter.cs:115)
SaveGamePro.SaveGameWriter.Write[Int32,Item] (System.Collections.Generic.Dictionary`2 obj) (at Assets/SaveGamePro/Scripts/SaveGameWriter.cs:203)
SaveGamePro.SaveGame.Save[Int32,Item] (System.Collections.Generic.Dictionary`2 obj, System.String identifier) (at Assets/SaveGamePro/Scripts/SaveGame.cs:299)
Inventory.AddItemToPlayerInventory (Int32 item_id, Int32 to_add_count) (at Assets/Scripts/Inventory.cs:408)
Inventory.Update () (at Assets/Scripts/Inventory.cs:317)`



Also what is the difference between the Free and Pro versions ? I did not know that it also can be used for that purpose.

**Comment by hasanbayatme** [comment]
Open up `SaveGameTypeManager` script inside `SaveGamePro/Scripts` and add your type like other types to the dictionary.

The Pro version can almost everything but the free version can save simple data types likes ones you have.

Thanks.

**Comment by devingDev** [comment]
Thanks very much now it works! Had to add it there and now it works 👍 

I think it's worth it. Maybe I am gonna use the more pro features later on but more important, does it have the same features like the free version ? iOS and android (cross platform) and such?

I see free version has cloud but this not right? Also I read that encryption on iOs is forbidden did I read right or wrong?

I am going to use this on iOS (64 bit) mainly and Android too.

**Comment by hasanbayatme** [comment]
Yes, it worth it, because a new update is coming for pro version that will add hundreds of features.

[Take a look at features that going to be added](https://trello.com/c/SgYpFsfd/35-save-game-pro)

No, the features are different.

Yes, the free version has cloud support. Alos the encryption is forbidden on iOS but you can contact Apple and they will allow you to include encryption in your app.

You get the right package for use on these platforms.

I would be happy to listen to your opinions and ideas about the Save Game Pro Gold Update.

Hope you enjoy this.

Thanks.

**Comment by devingDev** [comment]
Awesome so many features!

I am not sure if I will need cloud support yet but it would be a good idea to save userdata so he can restore it later. But that is not my need right now. I just wanted a simple Save/Load asset and I didn't even think it could save my Dictionary like this and load it as easily. That is really great for me :)

One question..
On the trello site for Save Game Pro , under Cross platform , only Standalone (Windows, Mac, Linux) and Universal Windows Platform are ticked. iOS and Android have no ticks. Does that mean it does not have the ability to be used on iOS right now?

**Comment by hasanbayatme** [comment]
No, the platforms ticked are related to the new update, that means the new update implemented these platforms support. This is the version that is under development when i complete a platform implementation for the Gold Update then i will tick that platform.

I would be happy to see you in our communities.

[Join our Commnuities](https://github.com/BayatGames/Support#join-us)

[Follow our News](https://github.com/BayatGames/Support#follow-our-news)

All the bests.

Thanks.
