### ISSUE TITLE
Are these conditional compilation symbols in SaveGameSimpleEncoder.cs not wrong?

### ISSUE THREAD

**Issue by Ultroman** [BayatGames/Support#30]
They say:
    #if !UNITY_WSA || !UNITY_WINRT

Should they not say:
    #if !UNITY_WSA && !UNITY_WINRT

With ||, if it IS UNITY_WINRT, then !UNITY_WSA will let it enter, and it never gets to the check for !UNITY_WINRT.

Also, out of curiosity and because I'm making my own encoder, why are these symbols there? Do I need these in my own encoders?

**Comment by hasanbayatme** [comment]
Ah yeah, that should be modified to &&.

Those are added in there as the WebGL and Windows Universal platform didn't support certain APIs which were because of the IL2CPP limitations and the .NET versions, which I think now should be working fine.

**Comment by Ultroman** [comment]
Thanks a ton! Very helpful <3

**Comment by hasanbayatme** [comment]
Stay awesome 🎉
