### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LokiGrants** [BayatGames/Support#5]
Multiple save system. Making it easier than having to creating a workaround over all save data that it already does - my case using a custom class and saving it under different names - so that users can have quick saves, and many more in a blink of an eye.

**Comment by hasanbayatme** [comment]
Hi, Can you clarify your suggestion?

Thanks.

**Comment by LokiGrants** [comment]
The way it works now, I can create a class - let's call it: SaveData. In it save all data that I am going to load. Then save it as a SaveData with a name and thats it. If I do multiple names, I have multiple saves. But doing a list to load, for instance, I'd have to save not only the SaveData, but also a List of SavedData names, load that list, to let the person choose and then load the correct save. This is just an example of multiple saves in a game.

I'm suggesting to make this kind of thing a feature instead of having workarounds to achieve multiple saves in a  game.

**Comment by hasanbayatme** [comment]
Thanks for clarifying.
You can use Dictionary, List or any other key-value pair collection for such task, Or you can save them as individual files.
Also, it is not a workaround, it is the way of handling with data.
Thanks.
