### ISSUE TITLE
Saving unassigned AudioClips

### ISSUE THREAD

**Issue by dermarder** [BayatGames/Support#6]
Hello, first of all you did great work with this asset!

Im having a problem: 
I want to save the Gameobject which contains all my non static Gameobject as children(Items, moveable Doors...) so i can save all necessary Objects that could possibly change in runtime.

However, im having problems saving unassigned public AudioClip variables. Is there a way to make this work?

Thank you very much in advance.

Best regards
Tom

**Comment by hasanbayatme** [comment]
Hi, thanks, we glad you like it.
What is the problem with the unassigned AudioClip?
Do you getting any error message?
You can make the field non savable, also let me know which Save Game version you are using, Pro or Free.

Thanks.
Best Regards.

**Comment by dermarder** [comment]
Im using SaveGame Pro and get a Null reference Exception.
How can i make the field non Saveable?

Thanks!

**Comment by hasanbayatme** [comment]
Just add **NonSavable** or **NonSerialized** attribute to the specified field.

Thanks.

**Comment by dermarder** [comment]
That works great, thanks!
Unfortunately, im having more problems:

Im getting the following error using Save and Loadinto:
`StackOverflowException
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MonoProperty.GetValue (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoProperty.cs:297)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:299)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:405)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectWriter.Write (System.Object value) (at Assets/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectWriter.cs:348)
BayatGames.SaveGamePro.Se<message truncated>`

**Comment by hasanbayatme** [comment]
Do you can provide your email?
Let me send you the new version via email, then try it and let me know if you have same problem again.

Thanks.

**Comment by dermarder** [comment]
That would be great. My email is: forstech@outlook.de
Thank you!

**Comment by hasanbayatme** [comment]
Sent the email, but continue the issue here for further customers to refer them here for same issue.

**Comment by dermarder** [comment]
I got the mail and it fixed the error. So far so good. Thank you!
Now im experiencing the next error while saving:

UnassignedReferenceException: The variable characterRigidbody of CharacterFootsteps has not been assigned.
You probably need to assign the characterRigidbody variable of the CharacterFootsteps script in the inspector.

The strange thing is, the CharacterFootsteps script has nothing to do with the gameobject I want to save.
I already tried to downgrade my unity to Version 2017.2.1, but it didnt make a difference.
Would it be better to save only the active states of all children gameobjects and apply the states to the Objects on runtime?
If yes, what would be the best approach to do this?

Thank you very much in advance.

**Comment by hasanbayatme** [comment]
Here is a bit late, but as far as I know, you are trying to save a game object hierarchy and you need control over serialization of them, for example, checking some conditions, so for this, I need to add a new feature, but let me know what other things do you need that I include in the new version.
For example, you can save game object prefab identifier, then use that identifier to spawn object on load then apply saved state, it is the simplest approach.

Thanks.

**Comment by dermarder** [comment]
I managed to make everything work as it should by creating custom classes per documentation and saving my needed variables into them.

Thank you very much for your great support!
Of course i will leave a good rating at the Asset Store.

**Comment by hasanbayatme** [comment]
Thanks for letting me know, I glad you find out how to solve your issue.
Also, we are creating video tutorials for Save Game Pro and we will publish them soon on YouTube and Asset Store.

Hope this helps.
Thanks,.
