### ISSUE TITLE
Lots of errors on 2018.1

### ISSUE THREAD

**Issue by blitzcloud** [BayatGames/Support#7]
When is 2018.1 compatibility coming? There's a certain issue in unity 2017 android versions that forces me to use 2018.1

**Comment by hasanbayatme** [comment]
Hi.
Do you can specify which product you are using?
Also, what kind of errors you are receiving? The error messages.
Thanks.

**Comment by blitzcloud** [comment]
Savegame Gold Upgrade

Errors(9)

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_AudioClip.cs(48,38): error CS0143: The class `UnityEngine.AudioClip' has no constructors defined

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_LightProbes.cs(46,42): error CS0143: The class `UnityEngine.LightProbes' has no constructors defined

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_Motion.cs(45,32): error CS1540: Cannot access protected member `UnityEngine.Motion.Motion()' via a qualifier of type `UnityEngine.Motion'. The qualifier must be of type `BayatGames.SaveGamePro.Serialization.Types.SaveGameType_Motion' or derived from it

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_Motion.cs(45,32): error CS0122: `UnityEngine.Motion.Motion()' is inaccessible due to its protection level

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_Motion.cs(45,32): error CS0122: `UnityEngine.Motion.Motion()' is inaccessible due to its protection level

>Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_RuntimeAnimatorController.cs(45,70): error CS0122: `UnityEngine.RuntimeAnimatorController.RuntimeAnimatorController()' is inaccessible due to its protection level

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_Texture.cs(55,34): error CS1540: Cannot access protected member `UnityEngine.Texture.Texture()' via a qualifier of type `UnityEngine.Texture'. The qualifier must be of type `BayatGames.SaveGamePro.Serialization.Types.SaveGameType_Texture' or derived from it

>Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_Texture.cs(55,34): error CS0122: `UnityEngine.Texture.Texture()' is inaccessible due to its protection level

> Assets/BayatGames/SaveGamePro/Scripts/Serialization/Types/SaveGameType_VideoClip.cs(47,44): error CS0143: The class `UnityEngine.Video.VideoClip' has no constructors defined

**Comment by hasanbayatme** [comment]
Thanks for the information, but do you can let me know when these error occurs?
Does these errors occur when you are exporting to Android?
I don't have such errors on my side, also I tried it on other computers too, but no such errors, so may you provide more information on how and when the error happens?
Thanks.

**Comment by blitzcloud** [comment]
Tried it with a brand new project. Same errors.

It happens on Editor.

Deleted the package from my Roaming folder and re-downloaded, still happens.

Also, it's the pro edition of savegame.

Version is 2018.1.0b13

**Comment by hasanbayatme** [comment]
Unity 2018 is currently in Beta, so we don't make our package compatible with Beta versions as there are many breaking changes coming soon to them, so you need to wait for the official release of 2018.1, then we will publish an compatibility update at the time the 2018.1 comes out.
I would like to suggest you to use official or LTS versions, like 2017.3 is the latest official release.
Thanks.
